# Generated by Django 5.0.4 on 2024-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Reading', max_length=30),
            preserve_default=False,
        ),
    ]
