# Generated by Django 5.0.4 on 2024-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_date_of_birth_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='novel', max_length=30),
            preserve_default=False,
        ),
    ]
