# Generated by Django 5.0.6 on 2024-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_comment_rating_user_follows_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default=' /countyourpages/books/images/default.jpg', upload_to='images/genres'),
            preserve_default=False,
        ),
    ]
